### PR TITLE
Added 0 Command to C# Bot

### PR DESCRIPTION
**Pull request by Ocky-Public**
This was missing from the C# bot. Added it to correctly list moves and reach command 6.

### CODE REVIEW

**Comment by EntelectChallenge** [comment]
Thank you, did not notice this was missing

**Comment by Ocky-Public** [comment]
No problem, having fun picking at the engine and seeing how its made lol.

**Comment by Jugen** [comment]
There’s a discrepancy between:

2016-Bomberman/Reference Bots/C#/Reference/Commands/GameCommand.cs

and

Sample Bots/C#/Domain/Enums/Moves.cs

In the latter “do nothing" is zero (0), but in the former it is seven (7) ?

From: oOCKYOo 
Sent: Thursday, April 14, 2016 10:18 AM
To: EntelectChallenge/2016-Bomberman 
Subject: [EntelectChallenge/2016-Bomberman] Added 0 Command to C# Bot (#4)

This was missing from the C# bot. Added it to correctly list moves and reach command 6.

---

You can view, comment on, or merge this pull request online at:
  https://github.com/EntelectChallenge/2016-Bomberman/pull/4

Commit Summary
  a.. Added 0 Command to C# Bot 
File Changes
  a.. M Sample Bots/C#/Domain/Enums/Moves.cs (1) 
Patch Links:
  a.. https://github.com/EntelectChallenge/2016-Bomberman/pull/4.patch 
  b.. https://github.com/EntelectChallenge/2016-Bomberman/pull/4.diff

**Comment by EntelectChallenge** [comment]
Hi Jugen,

Any command other 1-6 will be accepted as a do nothing command

**Comment by Ocky-Public** [comment]
In the case I found, the sample bot was using the length of the enum to determine the random range with the top value (6) being excluded since there were only 6 members in it.You could add the do nothing as the last command, but the bot would still only random between 0 and 6 with 7 enum members.

Hope this helps :)

**Pull request merged**
